name: stemvn_bluecontrol
description: "Bluetooth application for controlling the STEMVN BOT"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
    android: true
    ios: true
    image_path: "assets/app_ico/1024.png"
    adaptive_icon_background: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
     - assets/launch_logo.png
     - assets/in_app_logo.png
     - assets/app_ico/1024.png
     - assets/app_icon.png